import inkex
from typing import Dict, Iterable, List, Optional, Set, Tuple
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from svg_to_spice import Wire, Component, Segment, Point
from svg_helpers import point_key, point_on_segment, point_to_segment_distance, dist




# ---------------------------------------------------------------------
# Net solving
# ---------------------------------------------------------------------



def endpoint_pins(
    point: "Point",
    components: List["Component"],
    tol: float,
) -> List["Pin"]:
    hits: List["Pin"] = []

    for comp in components:
        if comp.is_subckt:
            continue

        for pin in comp.pins.values():
            if pin_touches_point(pin, point, tol):
                hits.append(pin)

    return hits



def pin_touches_point(pin: "Pin", p: "Point", tol: float) -> bool:
    if pin.shape in {"line", "path"}:
        return dist(p, pin.a) <= tol or dist(p, pin.b) <= tol or point_on_segment(p, pin.a, pin.b, tol)

    if pin.shape in {"circle", "ellipse"} and pin.center is not None:
        return dist(p, pin.center) <= pin.radius + tol

    if pin.shape == "rect" and pin.bbox is not None:
        x1, y1, x2, y2 = pin.bbox
        return (x1 - tol) <= p[0] <= (x2 + tol) and (y1 - tol) <= p[1] <= (y2 + tol)

    return False

def pin_touches_segment(pin: "Pin", seg: "Segment", tol: float) -> bool:
    if pin.shape in {"line", "path"}:
        return (
            point_on_segment(pin.a, seg.a, seg.b, tol)
            or point_on_segment(pin.b, seg.a, seg.b, tol)
            or point_on_segment(seg.a, pin.a, pin.b, tol)
            or point_on_segment(seg.b, pin.a, pin.b, tol)
        )

    if pin.shape in {"circle", "ellipse"} and pin.center is not None:
        return point_to_segment_distance(pin.center, seg.a, seg.b) <= pin.radius + tol

    if pin.shape == "rect" and pin.bbox is not None:
        x1, y1, x2, y2 = pin.bbox
        corners = [(x1, y1), (x2, y1), (x2, y2), (x1, y2)]
        if pin_touches_point(pin, seg.a, tol) or pin_touches_point(pin, seg.b, tol):
            return True
        edges = list(zip(corners, corners[1:] + corners[:1]))
        return any(segment_intersection(seg.a, seg.b, a, b, tol) is not None for a, b in edges)

    return False


def net_for_wire_segment(
    s: "Segment",
    key_to_net: Dict[Tuple[int, int], str],
    tol: float,
) -> Optional[str]:
    return (
        key_to_net.get(point_key(s.a, tol))
        or key_to_net.get(point_key(s.b, tol))
    )


def pin_touching_nets(
    pin: "Pin",
    wires: List["Wire"],
    key_to_net: Dict[Tuple[int, int], str],
    tol: float,
) -> Set[str]:
    """
    A pin connects when its geometry touches a wire/path.

    Supported pin geometry:
        - line/path: wire touches the pin line/path within tolerance
        - circle/ellipse: wire endpoint inside or segment crosses the shape
        - rect: wire endpoint inside or segment crosses the box
    """
    nets: Set[str] = set()

    for _, seg in all_wire_segments(wires):

        if pin_touches_segment(pin, seg, tol):
            net = net_for_wire_segment(seg, key_to_net, tol)

            if net is not None:
                nets.add(net)

    return nets


def all_wire_segments(wires: List["Wire"]) -> List[Tuple[str, "Segment"]]:
    out: List[Tuple[str, "Segment"]] = []

    for w in wires:
        for s in w.segments:
            out.append((w.element_id, s))

    return out


# ---------------------------------------------------------------------
# Union find
# ---------------------------------------------------------------------

class DSU:
    def __init__(self) -> None:
        self.parent: Dict[Tuple[int, int], Tuple[int, int]] = {}

    def add(self, x: Tuple[int, int]) -> None:
        self.parent.setdefault(x, x)

    def find(self, x: Tuple[int, int]) -> Tuple[int, int]:
        self.add(x)

        if self.parent[x] != x:
            self.parent[x] = self.find(self.parent[x])

        return self.parent[x]

    def union(self, a: Tuple[int, int], b: Tuple[int, int]) -> None:
        ra = self.find(a)
        rb = self.find(b)

        if ra != rb:
            self.parent[rb] = ra



def build_wire_nets(wires, tol):
    """
    Build electrical nets from wire geometry.

    Connects:
        - endpoint to endpoint
        - endpoint to segment
        - segment chains within the same path

    Does NOT connect:
        - plain middle-to-middle visual crossings

    Named net behaviour:
        - if a wire/path title contains #28102, that wire contributes net name n28102
        - all connected wires inherit that net name
        - if multiple named wires are connected, names are combined with underscores
          e.g. n28102_n28103
        - if no named wires are present, autogenerated names N001, N002, etc. are used
    """

    import re

    segments = all_wire_segments(wires)
    dsu = DSU()

    wire_by_id = {
        w.element_id: w
        for w in wires
    }

    def safe_net_token(text):
        """
        Make a node/net token from a wire title.

        The title '#28102' becomes node '28102'.

        No 'n' prefix is added.
        """

        text = str(text).strip()

        if not text:
            return None

        # Keep simple SPICE-ish node characters.
        # Do NOT prefix numeric node names.
        text = re.sub(
            r"[^A-Za-z0-9_]+",
            "_",
            text,
        ).strip("_")

        if not text:
            return None

        return text


    def title_text_for_wire(wire):
        """
        Return the SVG title for the wire object.
        """

        for attr_name in (
            "title",
            "svg_title",
            "path_title",
            "element_title",
        ):

            value = getattr(
                wire,
                attr_name,
                None,
            )

            if value:
                return str(value).strip()

        return ""


    def named_nets_for_wire(wire):
        """
        Extract node names from wire title.

        Rule:
            Title must start with '#'.

        Examples:
            '#28102'      -> {'28102'}
            '#BAT_POS'    -> {'BAT_POS'}
            '#IN'         -> {'IN'}
            'wire #28102' -> set()
        """

        title = title_text_for_wire(wire)

        if not title:
            return set()

        title = title.strip()

        # User rule:
        # the title defines a node only when the hash is at the front.
        if not title.startswith("#"):
            return set()

        token = title[1:].strip()

        name = safe_net_token(token)

        if not name:
            return set()

        return {name}   

    # ---------------------------------------------------------
    # Only real segment endpoints are allowed to become junction
    # candidates.
    # ---------------------------------------------------------

    points = []

    for wire_id, s in segments:

        points.append(s.a)
        points.append(s.b)

    # Add every endpoint to the union-find.

    for p in points:

        dsu.add(
            point_key(
                p,
                tol,
            )
        )

    # ---------------------------------------------------------
    # For each segment, find all existing endpoints that lie on it.
    # Then union them along that segment.
    # ---------------------------------------------------------

    for wire_id, s in segments:

        ax, ay = s.a
        bx, by = s.b

        dx = bx - ax
        dy = by - ay

        length2 = dx * dx + dy * dy

        if length2 <= tol * tol:
            continue

        on_this = []

        for p in points:

            if point_on_segment(
                p,
                s.a,
                s.b,
                tol,
            ):

                t = (
                    ((p[0] - ax) * dx + (p[1] - ay) * dy)
                    / length2
                )

                on_this.append(
                    (
                        max(
                            0.0,
                            min(
                                1.0,
                                t,
                            ),
                        ),
                        point_key(
                            p,
                            tol,
                        ),
                    )
                )

        on_this.sort(
            key=lambda item: item[0],
        )

        # Remove duplicate endpoint keys.

        unique_on_this = []

        last_key = None

        for t, key in on_this:

            if key != last_key:

                unique_on_this.append(
                    (
                        t,
                        key,
                    )
                )

                last_key = key

        # If two or more known endpoints lie on this segment,
        # they are electrically connected by this segment.

        for item1, item2 in zip(
            unique_on_this,
            unique_on_this[1:],
        ):

            k1 = item1[1]
            k2 = item2[1]


            dsu.union(
                k1,
                k2,
            )

    # ---------------------------------------------------------
    # Collect roots after all unions are complete.
    # ---------------------------------------------------------

    roots = sorted(
        {
            dsu.find(k)
            for k in dsu.parent
        }
    )

    # ---------------------------------------------------------
    # Collect title-based net names for each connected root.
    # ---------------------------------------------------------

    root_to_named_nets = {
        root: set()
        for root in roots
    }

    for wire_id, s in segments:

        wire = wire_by_id.get(wire_id)

        if wire is None:
            continue

        wire_named_nets = named_nets_for_wire(wire)

        if not wire_named_nets:
            continue

        # Either endpoint belongs to the same electrical root
        # after the union process.
        root = dsu.find(
            point_key(
                s.a,
                tol,
            )
        )

        root_to_named_nets.setdefault(
            root,
            set(),
        ).update(
            wire_named_nets
        )

    # ---------------------------------------------------------
    # Assign final net names.
    #
    # Priority:
    #   1. explicit title-based names
    #   2. autogenerated N001, N002, etc.
    # ---------------------------------------------------------

    root_to_net = {}

    unnamed_index = 1

    for root in roots:

        named_nets = sorted(
            root_to_named_nets.get(
                root,
                set(),
            ),
            key=lambda name: name.lower(),
        )

        if named_nets:

            net_name = named_nets[0]


            root_to_net[root] = net_name

        else:

            root_to_net[root] = f"N{unnamed_index:03d}"
            unnamed_index += 1

    # ---------------------------------------------------------
    # Build endpoint-key to net-name map.
    # ---------------------------------------------------------

    key_to_net = {
        k: root_to_net[
            dsu.find(k)
        ]
        for k in dsu.parent
    }
    
    inkex.utils.debug("===== FINAL WIRE NETS =====")

    for wire in wires:

        wire_nets = set()

        for seg in wire.segments:

            net = net_for_wire_segment(
                seg,
                key_to_net,
                tol,
            )

            if net:
                wire_nets.add(net)

        inkex.utils.debug(
            f'WIRE id="{wire.element_id}" '
            f'title="{wire.title}" '
            f'nets={sorted(wire_nets)}'
        )

    return key_to_net, dsu
